<div class="page-title">
	<h1><?php echo $this->__('Advertising - Add') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="form-validate-advertizement" enctype="multipart/form-data">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey') ?>
		<h2 class="legend"><?php echo $this->__('Advertising  Information') ?></h2>
			<ul class="form-list">
				<li>
				<div class="field">
					<label for="stores" class="required"><em>*</em><?php echo $this->__('Store') ?></label>
					<div class="input-box">
						<?php
						$Stores=array();
						$storeCollection=Mage::getModel('core/store_group')->getCollection();
						foreach($storeCollection as $store) {
							$storelang= Mage::getStoreConfig('general/locale/code', $store->getId());
							$Stores[]=$store->getData();
						}
						?>
						<select name="stores" id="stores" class="required-entry select" onchange="callController(this.value);">
							<option value="" selected="selected"><?php echo $this->__('Please Select Store--'); ?></option>
							<?php foreach($Stores as $eachstore) { ?>
								<option value="<?php echo $eachstore['default_store_id']; ?>"><?php echo $eachstore['name']; ?></option>
							<?php } ?>
						</select>
					</div>
				</div>			
			</li>
			
			
            <li>
                <div class="field">
                    <label for="category" class="required"><em>*</em><?php echo $this->__('Product Category') ?></label>
                    <div class="input-box" id="category_html">						
                    </div>
                </div>
                </li>
                <li>
		<div class="field">
					<div class="upload-head">
						<label for="image" class="required"><?php echo $this->__('Upload Image') ?></label>
					</div>
        <div class="input-box">
            <input type="file" id="advertizement-image" name="advertizement-image"  title="<?php echo $this->__('Image') ?>" class="input-text required-entry" />
         </div>
        </div>
			</li>
		<li>
			<div class="field">
				<div class="upload-head">
					<label for="image" class="required"><?php echo $this->__('Page Location') ?></label>
				</div>
				<select name="page_location" id="page_location" class="required-entry select">;	
					<option value="bottom">Bottom</option>
					<option value="right">Right</option>
				</select>
			</div>
		</li>
                <li>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link">
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
                <small>&laquo; </small>
                <?php echo $this->__('Back') ?>
            </a>
        </p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
var productForm = new VarienForm('form-validate-advertizement', true);
//]]>
function callController(sid) {
	new Ajax.Request("<?php echo $this->getUrl('advertizement/index/gettoreategory') ?>", {
		method: 'Post',
		parameters: {'store_id':sid},
		onComplete: function(transport) {
			document.getElementById('category_html').innerHTML=transport.responseText;
			alert(transport.responseText);
			//alert(sid);
		}
	});
}
</script>